### ISSUE TITLE
Can't get the tags correctly

### ISSUE THREAD

**Issue by MikiraSora** [mpatric/mp3agic#100]
I have some songs ,and these can display their tag in MusicPlayer App,such as Artists and Title.
But I wanted to make use of mp3agic to decode them and got error messy and nonsensical string . I used songs in other folders and it's worked successfully .GetEncode() always return null;
here is my part codw of getting tag:
  String getTitle(String path)throws{
                Mp3File file=new Mp3File(path);
		if(file==null)
			return "unknown";
		String val="unknown";
		if(file.hasId3v1Tag()){
			val=file.getId3v1Tag().getTitle();
			if(val.length()!=0)
				return val;
		}

**Comment by MikiraSora** [comment]
here is problem mp3 file:
http://z.qpan.wang/o_1akarnjr01ldngdv1uqb1l5t18m5a.mp3

**Comment by mpatric** [comment]
The example mp3 details example app https://github.com/mpatric/mp3agic-examples/blob/master/src/main/java/com/mpatric/mp3agic/app/Mp3Details.java looks to parse this mp3 file fine (see the output below), look at this example to see how to use mp3agic correctly. The getEncoder() method is returning null because there is no encoder field (TENC) in the idv32 tag.

```
MP3 Data
  Filename:        o_1akarnjr01ldngdv1uqb1l5t18m5a.mp3
  Size:            12436548
  Length:          4:59
  Version:         1.0
  Layer:           III
  Sample rate:     44100 Hz
  Bitrate:         320 kbps (CBR)
  Channel mode:    Joint stereo
ID3v1 Data
  Track:           
  Artist:          6*
  Title:           UjKnr
  Album:           KSL Live World 2008 ^Way to th
  Year:            2008
  Genre:           Soundtrack
  Comment:         
ID3v2 Data
  Track:           13
  Artist:          茶太
  Album:           KSL Live World 2008 ～Way to the Little Busters! EX～ [Disc 1]
  Title:           小さな手のひら
  Year:            2008
  Genre:           Soundtrack
  Comment:         null
  Composer:        null
  Original Artist: null
  Copyright:       null
  Url:             null
  Encoder:         null
  Album Image:     image/jpeg
Custom Tag
  NONE!
```
