### ISSUE TITLE
not able to set ImageView with album art

### ISSUE THREAD

**Issue by vish9496** [mpatric/mp3agic#102]
byte[] albumImageData = id3v2Tag.getAlbumImage();

Bitmap img = BitmapFactory.decodeByteArray(albumImageData,0,albumImageData.length,options);
coverart.setImageBitmap(img);// not working 
//not able to retrieve album art, album mimeType and length is retrievable but not able to convert to bitmap for viewing inside an imageview/imagebutton

[AlbumArtTest.zip](https://github.com/mpatric/mp3agic/files/347951/AlbumArtTest.zip)

**Comment by mpatric** [comment]
This looks to be an issue with the way you're using BitmapFactory rather than an issue with mp3agic.

**Comment by vish9496** [comment]
thank you.
