### ISSUE TITLE
Exception in thread "main" com.mpatric.mp3agic.InvalidDataException: No mpegs frames found

### ISSUE THREAD

**Issue by antflga** [mpatric/mp3agic#103]
This error would generally mean that the mp3 file is invalid correct?

I filter my music directory for files ending in .mp3, so I'm not trying to turn any non-mp3 files into mp3's, I know for a fact all of my music is valid, and yet I'm getting this error.

What things should I be checking

**Comment by mpatric** [comment]
You can give any file an mp3 extension, whether it's a valid mp3 or not. I suspect the file giving the error is an audio file, but not an mp3.
