### ISSUE TITLE
Coverage

### ISSUE THREAD

**Issue by SirWindfield** [mpatric/mp3agic#106]
I have some spare time at the weekend. If you guys need some help on writing unit tests/documentation, let me know :)

**Comment by hennr** [comment]
Thanks for the offer but I don't have time for a review at the moment.
If you want to, just send a PR and wait for me (low chance) or @mpatric to merge it.

**Comment by SirWindfield** [comment]
Might I ask if the project is still active in development?

**Comment by hennr** [comment]
Well, more or less it is.
We should think about allowing other people to commit though.
What do you think @mpatric?

**Comment by mpatric** [comment]
@hennr I'd be happy to add more committers to the project as I currently have very little time to spare
