### ISSUE TITLE
Can I use it for android?

### ISSUE THREAD

**Issue by faiznoeris** [mpatric/mp3agic#110]
When i try it, i got this error
> Information:Gradle tasks [:app:assembleDebug]
Error:PARSE ERROR:
Error:unsupported class file version 52.0
Error:...while parsing com/mpatric/mp3agic/AbstractID3v2FrameData.class
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: java.lang.UnsupportedOperationException
Information:BUILD FAILED
Information:Total time: 9.272 secs
Information:5 errors
Information:0 warnings
Information:See complete output in console

here's the code
```
Mp3File mp3file = null;
                try{
                    mp3file = new Mp3File("/storage/emulated/0/Music/music1.mp3");
                }catch (IOException e){
                    Toast.makeText(getApplicationContext(),"NULL",Toast.LENGTH_LONG).show();
                }catch (UnsupportedTagException e){
                    Toast.makeText(getApplicationContext(),"NULL",Toast.LENGTH_LONG).show();
                }catch (InvalidDataException e){
                    Toast.makeText(getApplicationContext(),"NULL",Toast.LENGTH_LONG).show();
                }catch (UnsupportedOperationException e){
                    Toast.makeText(getApplicationContext(),"NULL",Toast.LENGTH_LONG).show();
                }
```

                `ID3v1` id3v1Tag;
                if(mp3file.hasId3v1Tag()) {
                    id3v1Tag = mp3file.getId3v1Tag();
                    Toast.makeText(getApplicationContext(),id3v1Tag.getArtist(),Toast.LENGTH_LONG).show();
                }`

**Comment by hennr** [comment]
This seems to be about the java version.
mp3agic requires java 8 which android does not at this moment, so the answer is not at the moment, sorry.

**Comment by cinder92** [comment]
:( please make it usable for android

**Comment by hiteshsahu** [comment]
Android support Java 8 now

Add  

```
android {
    compileSdkVersion 27
    buildToolsVersion "27.0.3"
..
..
..
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

```
