### ISSUE TITLE
Facing problem while building

### ISSUE THREAD

**Issue by kvsjxd** [mpatric/mp3agic#111]
![screenshot_20161203_164642](https://cloud.githubusercontent.com/assets/17274550/20859002/753068f0-b978-11e6-8eb5-f06dcf153146.png)

**Comment by hennr** [comment]
This seems to be a problem in your environment, the master is fine:
https://travis-ci.org/mpatric/mp3agic/builds/181004355

I have also no problems with builing the 0.8.4 tag on my machine, sorry.

**Comment by kvsjxd** [comment]
I see, I will try building again but now on a fresh VM
