### ISSUE TITLE
Doesn't work at all for me

### ISSUE THREAD

**Issue by paul-kline** [mpatric/mp3agic#114]
I have tried a number of ways, but here is some code that doesn't work at all and always throws a Random access file error:

try {
                    Mp3File mp3file = new Mp3File(fullpathfile);
                    ID3v2 id3v2Tag;
                    if (mp3file.hasId3v2Tag()) {
                        id3v2Tag = mp3file.getId3v2Tag();
                    } else {
                        // mp3 does not have an ID3v2 tag, let's create one..
                        id3v2Tag = new ID3v24Tag();
                        mp3file.setId3v2Tag(id3v2Tag);
                    }
                    id3v2Tag.setTrack("" + 1);
                    id3v2Tag.setArtist(scheduleEntry.getMyStream().getName() + " Recording");
                    id3v2Tag.setTitle(scheduleEntry.getName());
                    id3v2Tag.setAlbum("The Album");
                    id3v2Tag.setYear("" + scheduleEntry.getEndingDate().getYear());
                    id3v2Tag.setGenre(12);
                    id3v2Tag.setComment("Paul Rocks");
                    mp3file.save("data_" + fullpathfile);
                } catch (UnsupportedTagException ex) {
                    Logger.getLogger(StreamRipper.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InvalidDataException ex) {
                    Logger.getLogger(StreamRipper.class.getName()).log(Level.SEVERE, null, ex);
                } catch (NotSupportedException ex) {
                    Logger.getLogger(StreamRipper.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception e) {
                    System.out.println("something when wrong saving stupid mp3 meta data");
                    e.printStackTrace();
                }

**Comment by hennr** [comment]
Code works fine for me with a random file I used.
Please re-open if you can deliver a files with which this code fails.
