### ISSUE TITLE
Genre and Genre Description are inconsistent with other attributes

### ISSUE THREAD

**Issue by tmzkt** [mpatric/mp3agic#120]
In ID3Wrapper.java, the code for `getGenre()` and `getGenreDescription()` prefer `id3v1Tag` over `id3v2Tag`. For all other attributes in ID3Wrapper.java, `id3v2Tag` is preferred over `id3v1Tag`. Genre and Genre Description are inconsistent with other attributes.

Please see [this pull request](https://github.com/mpatric/mp3agic/pull/119) for more information.

The purpose of this issue is to collect ideas and feedback on what _should_ be done, especially with input from @mpatric.
In my view, we either keep the functionality and document the reasons why or we resolve the inconsistency.

**Comment by hennr** [comment]
Thanks @tmzkt for bringing this up.
Did you find other code which still prefers v1 over v2? We should discuss them here as well.

**Comment by tmzkt** [comment]
Hi @hennr the only other code I found is in `Mp3File.init()` method where the v1 tag is initialized before the v2 tag.

So in summary,
1. ID3Wrapper - `getGenre()`
2. ID3Wrapper - `getGenreDescription()`
3. Mp3File - `init()`

I looked in every file, but it was not 100% exhaustive, so I might have missed something. Please mention any other instances that I overlooked.

**Comment by hennr** [comment]
Hi @tmzkt , I didn't find any other instances so far.
Question now is how to proceed. Switch to id3v2 everywhere and add a note in the changelog / readme or make it even configurable?

**Comment by tmzkt** [comment]
@hennr 
It really depends on how many users are relying on id3v1 being preferred before id3v2 for genre and genre description. I doubt that many users are relying on this, but I don't know for sure.
My instinct is to change it everywhere to be consistent and add a "breaking change" notification to the changelog / readme. Making it configurable would add additional complexity and is only useful if genre and genre description are truly a special case.

**Comment by hennr** [comment]
@tmzkt sounds good to me.

Are you ok with that way as well, @mpatric ?

**Comment by mpatric** [comment]
I agree, the wrapper functions should use `id3v2Tag` over `id3v1Tag`, with a breaking change notice in the release notes for the next release.

**Comment by hennr** [comment]
OK, sounds good.
@tmzkt Would you prepare a PR for this?

**Comment by tmzkt** [comment]
@hennr yes, I will create a pull request for the change. I am not sure where/how to change the release notes - is this something I should be changing as part of the pull request?

**Comment by hennr** [comment]
Sorry for the delay @tmzkt ,

there is no changelog yet. Would be great of you could simply add a file named changelog.md in the root of the project and add a hint under a
`# 0.10.0`
section.

**Comment by tmzkt** [comment]
No worries @hennr. Alright, I will put together a pull request complete with a changelog.md file in the coming days.

**Comment by jcgruenhage** [comment]
Nice that this was fixed. Are there any plans to make a release, so that people could benefit from this fix?

**Comment by mpatric** [comment]
Yeah, I'll do a release soon
