### ISSUE TITLE
Compiles with errors

### ISSUE THREAD

**Issue by ndasilva** [mpatric/mp3agic#126]
I downloaded the project and tried to build it prior to generate the JAR files which would be used in my own project. 

I opened mp3agic project as MAVEN project in Netbeans. 

After doing Clean and Build Project, I get the following message in the output window: 
`Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.016 sec <<< FAILURE! - in com.mpatric.mp3agic.FileWrapperTest
shouldFailForMalformedFilename(com.mpatric.mp3agic.FileWrapperTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<java.io.FileNotFoundException> but was<java.nio.file.InvalidPathException>
	at com.mpatric.mp3agic.FileWrapperTest.shouldFailForMalformedFilename(FileWrapperTest.java:35)`
Regards

**Comment by hennr** [comment]
That's strange as the project compiles at travis-ci.
Which operating system do you use?

**Comment by ndasilva** [comment]
Windows 7 PRO SP1 x64. 

Netbeans 8.2.

The following information has been copied from NetBeans "About" screen: 

`Product Version: NetBeans IDE 8.2 (Build 201609300101)
Updates: Updates available to version NetBeans 8.2 Patch 1
Java: 1.8.0_111; Java HotSpot(TM) 64-Bit Server VM 25.111-b14
Runtime: Java(TM) SE Runtime Environment 1.8.0_111-b14
System: Windows 7 version 6.1 running on amd64; Cp1252; en_GB (nb)`

I managed to build the project by commenting out that particular test. 

Regards. 

N
