### ISSUE TITLE
can't save lyric with Chinese

### ISSUE THREAD

**Issue by ironbear775** [mpatric/mp3agic#131]
I want to save lyric with Chinese. My code: 
tag = file.getId3v2Tag();
tag.setLyrics(s);
file.setId3v2Tag(tag);
        try {
            file.save(file.getFilename() + "_1");
            new File(file.getFilename()).delete();
            new File(file.getFilename() + "_1").renameTo(new File(file.getFilename()));
} catch (IOException | NotSupportedException e) {
            e.printStackTrace();
}

**Comment by tmzkt** [comment]
Thanks @ironbear775 for reporting this issue. I was able to reproduce the issue locally and have even seen some problems with attributes other than lyrics - such as comments and URL.
The core issue seems to be a flaw in the logic in the way the data is packed and unpacked using an encoding.
I will continue to understand the issue and see if I can make a fix for all the attributes affected.
