### ISSUE TITLE
Trouble in Different Answers On Converting From Seconds To Minutes

### ISSUE THREAD

**Issue by tusharshivan** [mpatric/mp3agic#142]
Hello There,
I was having a problem to get my understanding right for using Mp3Agic to get duration of MP3 file.

I used " mp3file.getLengthInSeconds " to get duration of a MP3 file but when I use calculator to convert them to minute, it doesn't show same duration of the MP3 file. But if I write a program to convert seconds to minutes, the calculation is same to the original duration. Why is THAT DIFFERENCE?

Thank You 
Tushar
![secondstominutes](https://user-images.githubusercontent.com/12612322/32696042-f23e5798-c792-11e7-9304-9b2c2b952af9.png)
![secondstominutes1](https://user-images.githubusercontent.com/12612322/32696043-f28d9fd8-c792-11e7-9d94-636a3fae7e3a.png)

**Comment by mpatric** [comment]
206 seconds is 3 minutes and 26 seconds (3.43333 minutes)

What are you expecting to see?

**Comment by tusharshivan** [comment]
Well if we do math, we divide seconds with 60. So if we divide 206 seconds with 60, we get 3:43 minute. But if I use / and %, I get true length of the file. Why is that?

**Comment by mpatric** [comment]
There are 60 seconds in a minute, not 100

**Comment by tusharshivan** [comment]
Thanks
