### ISSUE TITLE
Initialization IOException error

### ISSUE THREAD

**Issue by DogeMastr** [mpatric/mp3agic#148]
![image](https://user-images.githubusercontent.com/40916631/42422908-ae113f5c-82e7-11e8-879b-e2f69bf4316b.png)
Im using processing 3.3.7 as my IDE and ive imported your library and writing that gives me an IOException error, If i write it like this
![image](https://user-images.githubusercontent.com/40916631/42422917-f7e02ce2-82e7-11e8-8109-1ca06b177c25.png)
and it gives me this really long error that I don't know how to deal with.
This is the first line of your code form your examples and I feel like its meant to work
(also if I'm not meant to post it here could you tell me where)
Edit:
And then if I do this:
![image](https://user-images.githubusercontent.com/40916631/42423003-443863aa-82ea-11e8-873c-4e4f625415eb.png)
the constructor isn't visible..?

---
Doge

**Comment by dandanx** [comment]
Surround the instantiation with try catch.

See: https://docs.oracle.com/javase/tutorial/essential/exceptions/catch.html

**Comment by DogeMastr** [comment]
I dont know if im doing it right as im still getting an error
![image](https://user-images.githubusercontent.com/40916631/42423816-85d6e864-82f8-11e8-9e9a-c9bafc0d5c01.png)
