### ISSUE TITLE
Travis build failure (OracleJDK vs OpenJDK)

### ISSUE THREAD

**Issue by ullenius** [mpatric/mp3agic#165]
Travis fails using Oracle JDK 8 (see #164) . Oracle has changed the licence for Oracle JDK.

> 
> "The Oracle JDK License has changed for releases starting April 16, 2019.
> The new Oracle Technology Network License Agreement for Oracle Java SE is substantially different from prior Oracle JDK licenses."

Maybe the project should switch to using Open JDK 8? That should fix the Travis build issue as well. OpenJDK is the reference implementation, it's licensed under GPL 2 with classpath exception.

**External links for reference:**

https://launchpad.net/~webupd8team/+archive/ubuntu/java
https://travis-ci.community/t/java-8-failing-download-failed-oracle-jdk-8-is-not-installed/1894

**Comment by hennr** [comment]
Hi @ullenius,

sorry, this project is in a bad shape, maintenance wise, at least.

I switched to openJDK for the travis builds at least. Thanks for rasing this issue.

Regards
Henner
