### ISSUE TITLE
Is this library still supported?

### ISSUE THREAD

**Issue by Paul6552** [mpatric/mp3agic#169]
Hello,
I would like to use this library in my future project. After searching a while I found this library. Code looks good, but not very well maintained. There are many pull-requests, a few good one from ullenius, but they are not merged and the last release was in 2017.

Is this project still supported or is it better to make a fork of it?

Or maybe someone can suggest another good library for editing mp3-tags

Thank you

**Comment by mpfthprblmtq** [comment]
Hi Paul,
I use this library in a stand-alone mp3 management app I’m working on, and it works great for my purposes.  I’m able to edit/add all of the standard tags and some more I didn’t even know about.  Can’t say much about the support, but I’ll vouch for the usability of the library!

**Comment by Ra-Na** [comment]
Me too

**Comment by hennr** [comment]
Hi Paul,

this lib is maintained by 3 people currently. We don't spend much time on the project though, that's true.
Forking the library is something I would not recommend anyways. This would leave you alone as the maintainer of a fork. Bringing the current pull requests into shape and help them getting merged is the way I would suggest if you need code from them.

If you just want to use mp3agic, you should be good to go already.
