### ISSUE TITLE
========= THIS LIBRARY SEEMS TO BE UNMAINTAINED =========

### ISSUE THREAD

**Issue by gringofe** [mpatric/mp3agic#178]
Just a quick headsup to new users: This library seems to be unmaintained. There are issues open which have been open for multiple YEARS.

**Comment by barbetb** [comment]
Agree, its a nice library and easy to use. I haven't found something comparable. It would be a shame if it would start to fall apart.

**Comment by mpatric** [comment]
It's not totally unmaintained. There are only 3 maintainers, we do review and merge suitable PRs. The issue log could use some tidying up. Yes, there are some that have been open for YEARS. If you have fixes to contribute go ahead. Thanks.
