### ISSUE TITLE
Changing existing ID3v1values doesn't work

### ISSUE THREAD

**Issue by Feedler-F** [mpatric/mp3agic#179]
This works fine:
`id3v1Tag = new ID3v1Tag();
mp3file.setId3v1Tag(id3v1Tag);
id3v1Tag.setArtist("Artist");
mp3file.save([...]);`

This works also fine if the specific field didn't have a value yet (this.mp3file.i3dv1Tag.artist = ""):
`if (mp3file.hasId3v1Tag()) {
     id3v1Tag =  mp3file.getId3v1Tag();
}
id3v1Tag.setArtist("Artist");
mp3file.save([...]);`

When a field of an existing ID3v1 object already has a value however, my newly created mp3-File will always retain the previous value. According to the variables view in debug mode, this is the case even though this.mp3file.i3dv1Tag.artist holds my newly entered value during this part of the code execution:
`if (hasId3v1Tag()) {
     ByteBuffer byteBuffer = ByteBuffer.wrap(id3v1Tag.toBytes());
     byteBuffer.rewind();
     saveFile.write(byteBuffer);
}
saveFile.close();`

Any idea what could be the reason?

**Comment by mpatric** [comment]
I don't know why this wouldn't work for you. Here's an example of it working, using one of the test mp3 files in src/test/resources:

```java
public void shouldUpdateV1tags() throws InvalidDataException, IOException, UnsupportedTagException, NotSupportedException {
  Mp3File mp3File = new Mp3File("src/test/resources/v1tag.mp3");
  final String newArtist = "A new artist";
  if (mp3File.hasId3v1Tag()) {
    ID3v1 id3v1Tag = mp3File.getId3v1Tag();
    System.out.println("Artist: " + id3v1Tag.getArtist());
    assertNotEquals(id3v1Tag.getArtist(), newArtist);
    // Update artist and save mp3 as new file
    id3v1Tag.setArtist(newArtist);
    String newFilename = "src/test/resources/v1tag-updated.mp3";
    mp3File.save(newFilename);
    // Re-open the new mp3 and check what the aritst is
    Mp3File mp3File2 = new Mp3File(newFilename);
    ID3v1 id3v1Tag2 = mp3File2.getId3v1Tag();
    System.out.println("Artist: " + id3v1Tag2.getArtist());
    assertEquals(id3v1Tag2.getArtist(), newArtist);
  }
}
```

**Comment by Feedler-F** [comment]
> I don't know why this wouldn't work for you. Here's an example of it working, using one of the test mp3 files in src/test/resources:
> 

Thanks for your response. The problem wasn't that I couldn't change the ID3v-Tags, but that the meta information of many of my mp3 files are saved in a different location, which Windows prioritizes over ID3v1 or ID3v2. Although I still have no idea where the information is stored exactly.
