### ISSUE TITLE
problem with setAlbumImage()

### ISSUE THREAD

**Issue by Jeky** [mpatric/mp3agic#19]
I write a code to save album image into an mp3 file. but seems unable to save image tag.
code:

```
        byte[] content = readImageContentFromFile("cover.jpg");
        Mp3File mp3file = new Mp3File("xxx.mp3");
        ID3v2 id3v2Tag;
        if (mp3file.hasId3v2Tag()) {
            id3v2Tag = mp3file.getId3v2Tag();
        } else {
            // mp3 does not have an ID3v2 tag, create one
            id3v2Tag = new ID3v24Tag();
            mp3file.setId3v2Tag(id3v2Tag);
        }
        id3v2Tag.setAlbumImage(content, "image/jpg");
        mp3file.save("xxx1.mp3");
```

**Comment by DanielYWoo** [comment]
I have the same problem with the latest version of mp3agic. Does it have any constraints on the album image? like size limit or format?

**Comment by sinuhepop** [comment]
Works ok for me in most players (VLC, iTunes, Toshiba Media Player [was in my computer by default]) but it won't show Windows Media Player, which show images for other mp3 files. I don't know if it depends on the format or size of the file.

**Comment by sinuhepop** [comment]
I've done some jUnit tests. I have an mp3 with an image visible using WMP. It has a ID3v23Tag.

    // It works just rewriting image on same tag
    @Test
    public void ok1() throws Exception {
        Mp3File mp3 = new Mp3File("src/test/resources/samples/summertime-with-image.mp3");
        String type = mp3.getId3v2Tag().getAlbumImageMimeType();
        byte[] bytes = mp3.getId3v2Tag().getAlbumImage();
        mp3.getId3v2Tag().setAlbumImage(bytes, type);
        mp3.save("src/test/resources/samples/summertime-ok1.mp3");
    }

    // It works writing image on new ID3v23Tag
    @Test
    public void ok2() throws Exception {
        Mp3File mp3 = new Mp3File("src/test/resources/samples/summertime-with-image.mp3");
        String type = mp3.getId3v2Tag().getAlbumImageMimeType();
        byte[] bytes = mp3.getId3v2Tag().getAlbumImage();
        mp3.setId3v2Tag(new ID3v23Tag());
        mp3.getId3v2Tag().setAlbumImage(bytes, type);
        mp3.save("src/test/resources/samples/summertime-ok2.mp3");
    }

    // It fails writing image on new ID3v22Tag or ID3v24Tag
    @Test
    public void ko1() throws Exception {
        Mp3File mp3 = new Mp3File("src/test/resources/samples/summertime-with-image.mp3");
        String type = mp3.getId3v2Tag().getAlbumImageMimeType();
        byte[] bytes = mp3.getId3v2Tag().getAlbumImage();
        mp3.setId3v2Tag(new ID3v24Tag());
        mp3.getId3v2Tag().setAlbumImage(bytes, type);
        mp3.save("src/test/resources/samples/summertime-ko1.mp3");
    }

    // It fails writing image on new ID3v23Tag in a file without tags
    @Test
    public void ko2() throws Exception {
        val mp3 = new Mp3File("src/test/resources/samples/sample-without-tags.mp3");
        val bytes = FileUtils.read(new File("src/test/resources/samples/summertime.jpg"));
        val tag = new ID3v23Tag();
        tag.setAlbumImage(bytes, "image/jpg");
        mp3.save("src/test/resources/samples/sample-with-image-ko2.mp3");
    }

I've attached both files. Hope it helps!


[mp3s.zip](https://github.com/mpatric/mp3agic/files/453704/mp3s.zip)

**Comment by MarvinStelter** [comment]
I use this code which is working well, maybe after years someone need it : 

 public fun addAudioCover(context : Context, cover : Bitmap){
        try {
            val fileUtils = FileUtils()
            val importedAudioPath = File(context.filesDir, "imported_audio.mp3")
            val outputAudioPath = File(context.filesDir, "cover_audio.mp3")
            val mp3file = Mp3File(importedAudioPath.toString())
            val bytes = fileUtils.bitmapToBytes(cover)
            if (mp3file.hasId3v2Tag()) {
                mp3file.id3v2Tag.setAlbumImage(bytes, "image/jpg")
                mp3file.save(importedAudioPath.toString())
            } else {
                // Handle the case where ID3v2 tag is not present
                if (!mp3file.hasId3v2Tag()) {
                    mp3file.id3v2Tag = ID3v24Tag()
                }

                mp3file.id3v2Tag.setAlbumImage(bytes, "image/jpg")
                mp3file.save(outputAudioPath.toString())
            }

        }catch (e : Exception){
            Log.e("MediaFileEditor", "Error: " + e)
            Toast.makeText(context, "Error: " + e, Toast.LENGTH_SHORT).show()
        }
    }
