### ISSUE TITLE
Can't figure out the save function

### ISSUE THREAD

**Issue by ghost** [mpatric/mp3agic#74]
Hi guys, 

I know this might seem like a dumb question, but I'm in the middle of writing a Java Swing GUI application that functions like MP3Tag (for educational purposes) and I'm currently writing my saveTag method to save the newly written tag data into the imported MP3 file.

![savetag method source](https://cloud.githubusercontent.com/assets/7536259/5550209/0435f362-8b6d-11e4-8560-0f367ed3ef77.JPG)

This is my saveTag method, commented to get the logic across. (see above)

![gui_example](https://cloud.githubusercontent.com/assets/7536259/5550226/64933a08-8b6d-11e4-8ea8-0c251d98ac56.JPG)

This (see above) is a picture of the GUI in action, the new tag data is taken from the JComboBox components and is set into the tag data, and all of this works. However, when the code gets to the Mp3File.save(); function, it doesn't seem to create a new file, and it continues to delete the original just fine. Any help with understanding how to use the save function would be very much appreciated. Thank you!!

**Comment by micfarados** [comment]
i'm newbie. how to open Mp3file with chooser?
because i just call the filename..
