### ISSUE TITLE
switch to java 7 packages?

### ISSUE THREAD

**Issue by hennr** [mpatric/mp3agic#76]
As java 8 is out for a while now and java 6 didn't see any updates since Feb 2013 (http://www.oracle.com/technetwork/java/javase/eol-135779.html#Java6-end-public-updates) I wonder if we could switch to distributing java 7 jars of mp3agic via mvn central.

Any vetos?

**Comment by patrikvarga** [comment]
I'd recommend going for Java 8 immediately.
Java SE 7 End of Public Updates was in April 2015.

**Comment by TJC** [comment]
+1 for Java 8

**Comment by TheDiamondYT1** [comment]
+1 Its really not hard to do

**Comment by mpatric** [comment]
Yup, fine by me if someone want to do it.

**Comment by TheDiamondYT1** [comment]
I might try at some point

**Comment by patrikvarga** [comment]
> Yup, fine by me if someone want to do it.

Just a cheeky question, will you have time to look at and approve any PR if it happens?
Biased question as I have an open PR since June, but I don't want to hijack this thread. However, seeing progress with other PRs would probably motivate contributors (including me). ;)

**Comment by hennr** [comment]
See #107
