### ISSUE TITLE
Is there any documentation?

### ISSUE THREAD

**Issue by unknownterror** [mpatric/mp3agic#77]
The library seems very nice, but how do you expect people to know how to use it if there is no documentation? I cannot tell if I can use the library to extract PCM or raw audio data from mp3s, even though the description implies that it can.

**Comment by mpatric** [comment]
The readme explains how to use the library and the unit tests along with the example code in the [mp3agic-examples](https://github.com/mpatric/mp3agic-examples) project demonstrate how to use it.

You can get information about the mpeg data, but it does not allow you to extract the actual audio data - you need an mpeg codec for that.
