### ISSUE TITLE
Add support for .flac?

### ISSUE THREAD

**Issue by tchoulihan** [mpatric/mp3agic#83]
I'd like to use this library for .flac also, but for some reason, when identifying a .flac file, it finds no id3v2 or id3v1 Tags. Could you verify this as well?

**Comment by dandanx** [comment]
.flac uses Vorbis Comment instead of id3.

See: http://en.wikipedia.org/wiki/Vorbis_comment

**Comment by tchoulihan** [comment]
Ah, gotcha, I'll see if I can find a library out there.
