### ISSUE TITLE
Wrong method call in the examples

### ISSUE THREAD

**Issue by jlundan** [mpatric/mp3agic#86]
On page 

https://github.com/mpatric/mp3agic

There is section called "opening an mp3 file", which has line 

System.out.println("Bitrate: " + mp3file.getLengthInSeconds() + " kbps " + (mp3file.isVbr() ? "(VBR)" : "(CBR)"));

in it. The output says bitrate but the method call gets the track length. I know, minor issue. Took me however some time to figure that out after copy-pasting the example and wondering why my bitrates look really weird. =) 

Anyways, thanks for nice library!

Cheers,
Juha

**Comment by mpatric** [comment]
Thanks, fixed in the readme and in [Example.java](https://github.com/mpatric/mp3agic-examples/blob/master/src/main/java/com/mpatric/mp3agic/example/Example.java) in mp3agic-examples
